name: Rust

on:
  push:
    branches: [ "main", "develop", "staging" ]
  pull_request:
    branches: [ "main", "develop", "staging" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      run: sudo apt-get install python3 python3-dev
    - name: Set up Rust
      run: sudo apt-get install cargo && rustup override set 1.81
    - uses: actions/checkout@v4
    - name: Set up a Python virtual environment (needed for maturin)
      run: python3 -m venv ./venv
    - name: Install Python deps
      run: ./venv/bin/pip3 install -r ./requirements.txt
    - name: Build the internal Rust library, install it as a Python module
      run: cd dlcplazacryptlib && VIRTUAL_ENV='../venv' ../venv/bin/maturin develop && cd ..
    - name: Run unit tests
      run: |
        ./venv/bin/python3 ./server/test_api_local.py
        ./venv/bin/python3 ./server/test_db.py
        ./venv/bin/python3 ./server/test_event.py
        ./venv/bin/python3 ./server/test_oracle.py
        ./venv/bin/python3 ./server/test_util.py

